version: '3.8'

services:
  app:
    build: .
    container_name: smart-stock-api
    restart: always
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - smart-stock-network

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: iagobruno
      MYSQL_DATABASE: smart-stock
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smart-stock-network

volumes:
  mysql_data:

networks:
  smart-stock-network:
    driver: bridge
